version: '3.3'
services:
  # 自定义的服务名
  database:
    # 镜像
    image: mongo
    restart: always
    # 卷
    #volumes:
    #  - /data/db:/data/db
    networks:
      - webapp-network
  web:
    # 构建目录
    build: ./
    # image: mock-data
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - 3004:3004
    networks:
      - webapp-network
    command: ["./wait-for-it.sh", "database:27017", "--strict", "--", "npm", "run", "serve"]
networks:
  webapp-network:
    driver: bridge
